"""Per-sensor prompt scaffolding.

Sensors return a 1-2 sentence natural-language `description` + a
low/medium/high confidence rating. The description is the only thing
that flows into the Director; keeping the schema this narrow shrinks
prompt + generation time without losing anything we use.

Two pieces compose the per-call prompt:
- BASE_WEBCAM_PROMPT / BASE_SCREEN_PROMPT: invariant scaffolding that
  asks for a 1-2 sentence factual description + a low/medium/high
  confidence rating. Always-on coverage of posture / presence / app /
  content.
- focus context (per-session, generated by `focus_classifier`):
  short hint about what on-task looks like for THIS specific focus.

The Runner composes the two at session start (and on "Change focus…")
and stores the composed string on each sensor.
"""

from __future__ import annotations


BASE_WEBCAM_PROMPT = """You are looking at one webcam frame of a developer at their desk.

Describe what you see in 1-2 short factual sentences. Cover whatever is
relevant from: is a person present? Posture (upright / slouching /
leaning in / head down)? Face distance from the screen? Alertness state
(alert / tired / exhausted)? Anything else notable about their state or
surroundings.

No judgment, no advice. Just what you observe.

Also rate your CONFIDENCE in your description:
- "high": the frame is clear and you're sure of what you see.
- "medium": some details are unclear (lighting, partial view, angle).
- "low": the frame is dark, blurry, or shows something ambiguous that
  you're guessing about.
"""


BASE_SCREEN_PROMPT = """You are looking at one screen capture from a developer's desktop.

Describe what you see in 1-2 short factual sentences. Cover whatever is
relevant: what app or website is in the foreground (be SPECIFIC — name
the app and what's open, e.g. "VS Code editing auth.py" not just "code
editor"; "YouTube playing a piano tutorial" not just "browser")? What
is the user doing? If there is a clearly destructive command visible
on screen (rm -rf, git push --force, DROP TABLE, kubectl delete,
terraform destroy, sudo versions of those), mention it explicitly in
your sentence.

No judgment, no advice. Just what you observe.

Also rate your CONFIDENCE in your description:
- "high": you can see the app and content clearly.
- "medium": you can see what's on screen but some details are unclear
  (small text, unfamiliar UI, partial window).
- "low": the screen is unclear, blank, or showing something you can't
  identify with much certainty.
"""


_JSON_TAIL = """\

Return ONE JSON object, nothing else. No prose, no markdown fences.

{
  "description": "<your 1-2 sentence factual description>",
  "confidence": "low" | "medium" | "high"
}
"""


def compose_sensor_prompt(base: str, focus_context: str) -> str:
    """Compose the final per-call system prompt: base scaffolding +
    per-session focus context + the JSON output instruction.

    Focus context is optional — if empty, sensors operate purely on
    the base prompt's universal description criteria (still useful,
    just no per-focus framing)."""
    parts = [base.rstrip()]
    if focus_context.strip():
        parts.append(
            f"\nContext for this session — the user said they're focused on a\n"
            f"specific thing. Use this as a hint about what's on-task vs drift,\n"
            f"but always still report what you actually see (don't omit obvious\n"
            f"posture / wellness signals just because they're off-topic):\n\n"
            f"  {focus_context.strip()}"
        )
    parts.append(_JSON_TAIL)
    return "\n".join(parts)
